name: CmdHider
version: 1.0.0
main: com.elimcgehee.cmdhider.CmdHiderPlugin
api-version: '1.21'
authors:
  - Eli
depend:
  - LuckPerms
commands:
  cmdhider:
    description: Reloads CmdHider configuration.
    usage: /cmdhider reload
    permission: cmdhider.admin
permissions:
  cmdhider.admin:
    description: Allows reloading CmdHider.
    default: op
